/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  desktopSidebar: [
    {
      type: "category",
      label: "电脑版文档",
      link: { type: "doc", id: "desktop/index" },
      items: [
        {
          type: "category",
          label: "常见问题︱其他问题",
          link: { type: "doc", id: "desktop/other" },
          items: [{ type: "autogenerated", dirName: "desktop/other" }],
        },
        {
          type: "category",
          label: "常见问题︱更新和安装",
          link: { type: "doc", id: "desktop/update-and-package" },
          items: [
            { type: "autogenerated", dirName: "desktop/update-and-package" },
          ],
        },
        {
          type: "category",
          label: "常见问题︱播放和下载",
          link: { type: "doc", id: "desktop/play-and-download" },
          items: [
            { type: "autogenerated", dirName: "desktop/play-and-download" },
          ],
        },
        {
          type: "category",
          label: "常见问题︱歌单和外部歌单",
          link: { type: "doc", id: "desktop/list-and-songlist" },
          items: [
            { type: "autogenerated", dirName: "desktop/list-and-songlist" },
          ],
        },
        {
          type: "category",
          label: "常见问题︱自定义源",
          link: { type: "doc", id: "desktop/source" },
          items: [{ type: "autogenerated", dirName: "desktop/source" }],
        },
        {
          type: "doc",
          id: "desktop/scheme-url", // document ID
          label: "Scheme URL支持", // sidebar label
        },
        {
          type: "doc",
          id: "desktop/run-params", // document ID
          label: "支持的启动参数", // sidebar label
        },
        {
          type: "doc",
          id: "desktop/datapath", // document ID
          label: "数据存储路径", // sidebar label
        },
        {
          type: "doc",
          id: "desktop/notsupported", // document ID
          label: "不支持的功能", // sidebar label
        },
        {
          type: "doc",
          id: "desktop/hotkey", // document ID
          label: "可用的快捷键", // sidebar label
        },
        {
          type: "doc",
          id: "desktop/use-source-code", // document ID
          label: "源码使用方法", // sidebar label
        },
        {
          type: "doc",
          id: "desktop/license", // document ID
          label: "许可协议", // sidebar label
        },
      ],
    },
  ],

  mobileSidebar: [
    {
      type: "category",
      label: "移动版文档",
      link: { type: "doc", id: "mobile/index" },
      items: [
        {
          type: "category",
          label: "常见问题︱其他问题",
          link: { type: "doc", id: "mobile/other" },
          items: [{ type: "autogenerated", dirName: "mobile/other" }],
        },
        {
          type: "category",
          label: "常见问题︱更新和安装",
          link: { type: "doc", id: "mobile/update-and-package" },
          items: [
            { type: "autogenerated", dirName: "mobile/update-and-package" },
          ],
        },
        {
          type: "category",
          label: "常见问题︱播放和下载",
          link: { type: "doc", id: "mobile/play" },
          items: [{ type: "autogenerated", dirName: "mobile/play" }],
        },
        {
          type: "category",
          label: "常见问题︱歌单和外部歌单",
          link: { type: "doc", id: "mobile/list-and-songlist" },
          items: [
            { type: "autogenerated", dirName: "mobile/list-and-songlist" },
          ],
        },
        {
          type: "doc",
          id: "mobile/statusbar-lyric", // document ID
          label: "状态栏歌词", // sidebar label
        },
        {
          type: "doc",
          id: "mobile/datapath", // document ID
          label: "数据存储路径", // sidebar label
        },
        {
          type: "doc",
          id: "mobile/use-source-code", // document ID
          label: "源码使用方法", // sidebar label
        },
        {
          type: "doc",
          id: "mobile/license", // document ID
          label: "许可协议", // sidebar label
        },
      ],
    },
  ],
};

module.exports = sidebars;
